//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueConsultingManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetPK { get; set; }
        public string DepartmentName { get; set; }
        public double DepartmentTotal { get; set; }
    }
}
