//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueConsultingManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public int ReportPK { get; set; }
        public string ReportName { get; set; }
        public string SuppervisorApproval { get; set; }
        public string StaffApproval { get; set; }
        public Nullable<System.DateTime> DateOfApproval { get; set; }
        public string Department { get; set; }
        public string SupervisorName { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
    }
}
