//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueManagementConsultingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.Supervisors = new HashSet<Supervisor>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public int BudgetID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentTotal { get; set; }
    
        public virtual ICollection<Supervisor> Supervisors { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
