//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueManagementConsultingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        public Consultant()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int ConsultantID { get; set; }
        public string ConsultantName { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
