//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueManagementConsultingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public int ReportId { get; set; }
        public string ReportName { get; set; }
        public string SupervisorName { get; set; }
        public Nullable<bool> StaffApproval { get; set; }
        public Nullable<bool> SupervisorApproval { get; set; }
        public string StaffDate { get; set; }
        public string DepartmentName { get; set; }
        public string StaffApprovalDate { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual Consultant Consultant { get; set; }
        public virtual Supervisor Supervisor { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
