//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueManagementConsultingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public Supervisor()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int SupervisorID { get; set; }
        public string SupervisorName { get; set; }
        public string DepartmentType { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
        public virtual Budget Budget { get; set; }
    }
}
